### ISSUE TITLE
serde_dhall::parse use blocking reqwest on remote import

### ISSUE THREAD

**Issue by fteychene** [dhall-mock/dhall-mock#30]
## How to reproduce
Launch the application with a dhall configuration that import remote configuration.
```dhall
let map = https://prelude.dhall-lang.org/List/map

let show = \(value : Natural) -> "${Natural/show value}"
in map Natural Text show [ 1, 2, 3 ]
```
The program should fail on loading the configuraton at the program startup

**Stacktrace** :
```
[2020-04-09T23:40:28Z INFO  dhall_mock] Start dhall mock project 👋
thread 'main' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', /home/fteychene/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.16/src/runtime/enter.rs:19:5
stack backtrace:
 ...
  22: reqwest::blocking::get
             at /home/fteychene/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.4/src/blocking/mod.rs:99
  23: dhall::semantics::parse::parse_remote
             at /home/fteychene/.cargo/registry/src/github.com-1ecc6299db9ec823/dhall-0.5.0/src/semantics/parse.rs:20
  24: dhall::Parsed::parse_remote
             at /home/fteychene/.cargo/registry/src/github.com-1ecc6299db9ec823/dhall-...
 ...
  66: dhall_mock::main
             at src/main.rs:15
  67: std::rt::lang_start::{{closure}}
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/rt.rs:67
  68: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  69: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  70: std::panicking::try
             at src/libstd/panicking.rs:274
  71: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  72: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  73: std::rt::lang_start
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/rt.rs:67
  74: main
  75: __libc_start_main
  76: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Description

[dhall-rust](https://github.com/Nadrieril/dhall-rust) use reqwest blocking client in it's internal when there is some remote lib to import.

Since we integrated hyper web server and the configuration to move in async we cant start another runtime or use blocking functions.

**Comment by fteychene** [comment]
Close by #35
